services:
  lsky-pro:
    image: ghcr.io/advfree/lsky-pro:latest
    container_name: lsky-pro
    restart: always
    ports:
      - "7791:80"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: lsky-pro
      MYSQL_USER: lsky-pro
      MYSQL_PASSWORD: your_mysql_password # 改成强密码，并与下面 MYSQL_PASSWORD 保持一致
    volumes:
      - /root/data/docker_data/lsky-pro/lsky-pro-data:/var/www/html/storage
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: lsky-pro-db
    restart: always
    environment:
      MYSQL_DATABASE: lsky-pro
      MYSQL_USER: lsky-pro
      MYSQL_PASSWORD: your_mysql_password # 改成强密码，并与上面 MYSQL_PASSWORD 保持一致
      MYSQL_ROOT_PASSWORD: your_mysql_root_password # 改成另一个强密码
    volumes:
      - /root/data/docker_data/lsky-pro/db:/var/lib/mysql
